config/routes.rb
OneClickOrgs::Application.routes.draw do

  
  match '/settings' => 'one_click#settings', :as => 'settings'
  match '/constitution' => 'one_click#constitution', :as => 'constitution'
  
  match '/timeline' => 'one_click#timeline', :as => 'timeline'
  
  match '/votes/vote_for/:id' => 'votes#vote_for', :conditions => {:method => :post}, :as => 'vote_for'
  match '/votes/vote_against/:id' => 'votes#vote_against', :conditions => {:method => :post}, :as => 'vote_against'
  
  resources :decisions
  resources :proposals
  match '/proposals(/:action)' => 'proposals'
  resources :members do
    member do
      post :change_class
    end
  end
  
  match '/one_click(/:action)' => 'one_click'
  match '/induction(/:action)' => 'induction'
  
  match '/login' => 'member_sessions#new', :as => 'login'
  resource :member_session, :only => [:new, :create, :destroy]
  
  match '/reset_password(/:action)' => 'reset_password'
  
  match '/welcome(/:action)' => 'welcome'
  
  match '/setup(/:action)' => 'setup'
  
  resources :organisations
  
  root :to => 'one_click#dashboard'
end

app/views/shared/_constitution.html.haml
%h4 Definitions & Membership
%ul.constitution
  %li
    This is the constitution ("Constitution") of
    %span{:class=>'dynamic'}
      = @organisation_name
    ("The Organisation").  
  %li
    The Organisation has the objectives of
    %span{:class=>'dynamic'}
      = @objectives
    ("Objectives").
  %li
    - if @assets
      The Organisation may hold, transfer and dispose of material assets and intangible assets.
    - else
      The Organisation does not hold material assets or intangible assets.
  %li The Organisation uses an electronic system to carry out its governance ("Governance System").
  %li The Organisation has one or more members ("Members") who support its Objectives. 
  %li Each Member nominates an email address at which they will receive important notices from the Organisation ("Nominated Email Address"). 
  %li
    Members may access the Governance System at the website
    %span{:class => 'dynamic'}
      = @website
  %li Members may view the current Constitution on the Governance System. 
  %li Members may view a register of current Members together with their Nominated Email Addresses on the Governance System. 
  %li Members may resign their membership via the Governance System.

%h4 Proposals & Decisions
%ul.constitution
  %li Members may jointly make a decision ("Decision") relating to any aspect of the Organisation's activities as follows:
  %li Any member may submit a proposal ("Proposal") on the Governance System. 
  %li
    A Proposal may be voted on for a period of
    %span{:class=>'dynamic'}
      = @voting_period
    starting with its submission ("Voting Period").
  %li Members may view all current Proposals on the Governance System. 
  %li Members may vote to support ("Supporting Vote") or vote to oppose ("Opposing Vote") a Proposal on the Governance System during the Proposal's Voting Period. 
  %li Members may only vote on Proposals submitted during their membership of the Organisation.
  %li
    A Decision is made if a Proposal receives
    %span{:class=>'dynamic'}
      = @general_voting_system.long_description
  %li except that:
  %li
    The Constitution may only be amended by a Decision where
    %span{:class=>'dynamic'}       
      = @constitution_voting_system.long_description(:include_received => true)
  %li and
  %li
    New Members may be appointed (and existing Members ejected) only by a Decision
    %span{:class=>'dynamic'}
      = @membership_voting_system.long_description(:include_received => true)
  %li Members may view all Decisions on the Governance System.

/ %h4 Proxies
/ %ul.constitution
/   %li A Member may nominate another Member as their proxy (“Proxy Nomination”) on the Management System. In this case the Member assigning the proxy is the proxy giver (“Proxy Giver”) and the nominated Member is the proxy holder (“Proxy Holder”). 
/   %li On each occasion a Proxy Holder submits a Supporting Vote or Opposing Vote equivalent votes shall be submitted for all Proxy Givers by whom they are currently nominated. 
/   %li A Proxy Holder may in turn nominate another Member as their proxy. 
/   %li A Member may withdraw a Proxy Nomination at any time on the Management System. 

/ %h4 Failsafe Clauses 
/ %ul.constitution
/   %li Should the Constitution be amended in such a way that an impasse arises any Member may submit a special proposal (“Reset Proposal”) to reset the Constitution to the default options for a General Decision, a Membership Decision and a Constitution Decision on the Management System.
/   %li A Reset Proposal is enacted if it receives Supporting Votes from more than two thirds of Members during the Voting Period.
/   %li Should the Management System become unavailable or defective such that it does not meet the requirements specified in the Constitution any Member may convene an emergency meeting (“Emergency Meeting”) by sending an email to all other Members at their Nominated Email Address stating a date and time at which the meeting shall commence.
/   %li An Emergency Meeting shall not be scheduled to commence less than seven days after it is convened except with unanimous written consent of the Members.
/   %li Should more than one Member send an email to convene an Emergency Meeting the one that was sent first shall have primacy.
/   %li An Emergency Meeting may be conducted in person, by any form of synchronous electronic communication or by a combination thereof.
/   %li At a duly convened Emergency Meeting the Members shall be able to make General Decisions on the basis described in the Constitution but stating “support” or “oppose” in place of the Management System.
/   %li Should the number of Members become zero the Custodian of CIRCUS foundation as named on the website CIRCUS-foundation.org/custodian shall have the right to appoint one, two or three new Members.

app/views/shared/_propose_change_objectives_form.html.haml
- if current_user.has_permission(:constitution_proposal)
  =form_tag(:controller => 'proposals', :action => 'create_text_amendment') do
    %div.constitution_proposal
      %p.reveal_link
        %a{:href => '#'}
          Propose an amendment
      %div.proposal_form{:style => 'display: none;'}
        %p
          %label{:for => 'value'}
            Change the organisation's objectives to:
          %textarea{:name => 'value'}= @objectives
          %input{:type => 'hidden', :name => 'name', :value => 'objectives'}
        %p
          = submit_tag "Propose change", :id => 'submit'
        %p
          %a{:href => '#', :class => 'cancel_link'}
            Cancel

app/views/shared/_propose_change_org_name_form.html.haml
- if current_user.has_permission(:constitution_proposal)
  =form_tag(:controller => 'proposals', :action => 'create_text_amendment') do
    %div.constitution_proposal
      %p.reveal_link
        %a{:href => '#'}
          Propose an amendment
      %div.proposal_form{:style => 'display: none;'}
        %p
          %label{:for => 'value'}
            Change the organisation's name to:
          %input{:name => 'value', :value => @organisation_name}
          %input{:type => 'hidden', :name => 'name', :value => 'organisation_name'}
        %p
          = submit_tag "Propose change", :id => 'submit'
        %p
          %a{:href => '#', :class => 'cancel_link'}
            Cancel

app/views/shared/_propose_change_voting_period_form.html.haml
- if current_user.has_permission(:constitution_proposal)
  =form_tag(:controller => 'proposals', :action => 'create_voting_period_amendment') do
    %div.constitution_proposal
      %p.reveal_link
        %a{:href => '#'}
          Propose an amendment
      %div.proposal_form{:style => 'display: none;'}
        %p
          %label{:for => 'new_voting_period'}
            Change the voting period to:
          %select{:name => 'new_voting_period'}
            - VotingPeriods.all do |vp|
              - if vp[:value] == @period
                %option{:value => vp[:value], :selected => true}= vp[:name]
              - else
                %option{:value => vp[:value]}= vp[:name]
        %p
          = submit_tag "Propose change", :id => 'submit'
        %p
          %a{:href => '#', :class => 'cancel_link'}
            Cancel

app/views/shared/_propose_freeform_form.html.haml
- if current_user.has_permission(:freeform_proposal)
  %h4 New Proposal
  = form_for(@new_proposal, :url => proposals_path, 'class' => 'proposal') do |f|
    %p
      = f.label(:title)
      = f.text_field :title
    %p
      = f.label(:description)
      = f. text_area :description
    %p
    = submit_tag "Create Proposal", :id => 'submit'

app/views/shared/_propose_hold_assets_form.html.haml
- if current_user.has_permission(:constitution_proposal)
  = form_tag(:controller => 'proposals', :action => 'create_assets_amendment') do
    %div.constitution_proposal
      %p.reveal_link
        %a{:href => '#'}
          Propose adding a clause to allow holding of assets
      %div.proposal_form{:style => 'display: none;'}
        %p
          Propose that the organisation should be allowed to hold, transfer or dispose of material assets and intangible assets.
        %input{:type => 'hidden', :name => 'new_assets_value', :value => '1'}
        %p
          = submit_tag "Propose change", :id => 'submit'
        %p
          %a{:href => '#', :class => 'cancel_link'}
            Cancel

app/views/shared/_propose_hold_no_assets_form.html.haml
- if current_user.has_permission(:constitution_proposal)
  =form_tag(:controller => 'proposals', :action => 'create_assets_amendment') do
    %div.constitution_proposal
      %p.reveal_link
        %a{:href => '#'}
          Propose an amendment
      %div.proposal_form{:style => 'display: none;'}
        %p
          Propose that the organisation should <strong>not</strong> be allowed to hold, transfer or dispose of material assets and intangible assets.
        %input{:type => 'hidden', :name => 'new_assets_value', :value => '0'}
        %p
          = submit_tag "Propose change", :id => 'submit'
        %p
          %a{:href => '#', :class => 'cancel_link'}
            Cancel

app/views/shared/_propose_new_member_form.html.haml
- if current_user.has_permission(:membership_proposal)
  %h4
    Propose a new member
  %p
    = form_for(@new_member, :as => :member, :url => members_path) do |f|
      %p
        = f.label(:email, "Email Address")
        = f.text_field :email
      %p
        = f.label(:first_name)
        = f.text_field :first_name
      %p
        = f.label(:last_name)
        = f.text_field :last_name
      %p
        = f.label(:class)
        = collection_select(:member, :member_class_id, MemberClass.all, :id, :name)
      %p
        = submit_tag "Add Member", :id => 'submit'

app/views/shared/_propose_voting_system_amendment_form.html.haml
- if current_user.has_permission(:constitution_proposal)
  =form_tag(:controller => 'proposals', :action => 'create_voting_system_amendment') do
    %div.constitution_proposal
      %p.reveal_link
        %a{:href => '#'}
          Propose an amendment
      %div.proposal_form{:style => 'display: none;'}
        %p
          =render :partial => 'voting_system_field', :locals => {:type => type, :description => description}
        %p
          =submit_tag "Propose change", :id => 'submit'
        %p
          %a{:href => '#', :class => 'cancel_link'}
            Cancel