config/routes.rb
OneClickOrgs::Application.routes.draw do

  
  match '/settings' => 'one_click#settings', :as => 'settings'
  match '/constitution' => 'one_click#constitution', :as => 'constitution'
  
  match '/timeline' => 'one_click#timeline', :as => 'timeline'
  
  match '/votes/vote_for/:id' => 'votes#vote_for', :conditions => {:method => :post}, :as => 'vote_for'
  match '/votes/vote_against/:id' => 'votes#vote_against', :conditions => {:method => :post}, :as => 'vote_against'
  
  resources :decisions
  resources :proposals
  match '/proposals(/:action)' => 'proposals'
  resources :members do
    member do
      post :change_class
    end
  end
  
  match '/one_click(/:action)' => 'one_click'
  match '/induction(/:action)' => 'induction'
  
  match '/login' => 'member_sessions#new', :as => 'login'
  resource :member_session, :only => [:new, :create, :destroy]
  
  match '/reset_password(/:action)' => 'reset_password'
  
  match '/welcome(/:action)' => 'welcome'
  
  match '/setup(/:action)' => 'setup'
  
  resources :organisations
  
  root :to => 'one_click#dashboard'
end

app/controllers/one_click_controller.rb
class OneClickController < ApplicationController
  
  def index
    redirect_to(:action => 'dashboard')
  end
  
  def constitution
    prepare_constitution_view
  end
  
  def dashboard
    # only_provides :html
    
    # Fetch open proposals
    @proposals = co.proposals.currently_open
    
    @new_proposal = co.proposals.new
    @new_member = co.members.new
    
    @timeline = [
      co.members.all,
      co.proposals.all,
      co.decisions.all
    ].flatten.map(&:to_event).compact.sort{|a, b| b[:timestamp] <=> a[:timestamp]}
  end
  
  def settings
    prepare_constitution_view
  end
  
end

app/helpers/one_click_helper.rb
module OneClickHelper
end

app/views/one_click/_decision.html.haml
%td= event[:timestamp].to_s(:long)
%td
  A decision was made:
  = link_to(event[:object].proposal.title, proposal_path(event[:object].proposal))

app/views/one_click/_failed_proposal.html.haml
%td= event[:timestamp].to_s(:long)
%td
  A proposal failed:
  = link_to(event[:object].title, proposal_path(event[:object]))

app/views/one_click/_new_member.html.haml
%td= event[:timestamp].to_s(:long)
%td
  New member:
  = link_to(event[:object].name, member_path(event[:object]))

app/views/one_click/_proposal.html.haml
%td= event[:timestamp].to_s(:long)
%td
  A proposal was made:
  = link_to(event[:object].title, proposal_path(event[:object]))

app/views/one_click/_vote.html.haml
%td= event[:timestamp].to_s(:long)
%td
  A vote was made on the proposal:
  = link_to(event[:object].proposal.title, proposal_path(event[:object].proposal))

app/views/one_click/_voting_system_field.html.haml
%label{:for => "#{type}_voting_system"}= description
%select{:name=>"#{type}_voting_system"}
  - VotingSystems.all do |vs|
    - if vs.simple_name == instance_variable_get("@#{type}_voting_system".to_sym)
      %option{:value => vs.simple_name, :selected => true}= vs.description
    - else
      %option{:value=>vs.simple_name}= vs.description        

app/views/one_click/constitution.html.haml
%h3 Constitution

=render :partial => 'shared/constitution'

app/views/one_click/dashboard.html.haml
%h3 Dashboard

%p= "Welcome back, #{current_user.name}!" if current_user

= render :partial => 'shared/propose_freeform_form'
  
= render :partial => 'shared/propose_new_member_form'

%h4 Votes in progress
%table.proposals
  %tr
    %th Title
    %th Ends
    %th For/against
    %th Your Vote
  - for proposal in @proposals
    %tr{:class => cycle('odd', 'even')}
      %td
        = proposal.title
        (
        = link_to(proposal.proposer.name, member_path(proposal.proposer))
        )
        = render 'proposals/description', :proposal => proposal
        %p= link_to("More details", proposal_path(proposal))
      %td.timestamp
        = distance_of_time_in_words_to_now(proposal.end_date)
        (
        = proposal.end_date.to_s(:long)
        )
      %td 
        = render 'proposals/vote_count', :proposal => proposal
      %td.vote
        = render 'proposals/vote', :proposal => proposal
  
%h4 Timeline
%table.timeline
  - for event in @timeline
    %tr
      = render :partial => event[:kind].to_s, :locals => {:event => event}

app/views/one_click/login.html.haml
%h3 Please Login

= form_tag(:controller => :one_click, :action => :authenticate) do
  = label_tag(:email)
  = text_field_tag :email
  %br
  = label_tag(:password)
  = password_field_tag :password
  %br
  = submit_tag "Login", :id => 'submit'
  %br

app/views/one_click/settings.html.haml
%h3 Settings

%dl.settings
  %dt Organisation name
  %dd
    = render :partial => 'shared/propose_change_org_name_form'
    = @organisation_name
  %dt Objectives
  %dd
    = render :partial => 'shared/propose_change_objectives_form'
    = @objectives
  %dt Assets
  %dd
    - if @assets
      = render :partial => 'shared/propose_hold_no_assets_form'
      The Organisation may hold, transfer and dispose of material assets and intangible assets
    - else
      = render :partial => 'shared/propose_hold_assets_form'
      The Organisation does not hold material assets or intangible assets.
  %dt Making decisions
  %dd
    = render :partial => 'shared/propose_voting_system_amendment_form', :locals => {:type => 'general', :description => 'Change the way decisions are made:'}
    A decision is made if a proposal receives
    = @general_voting_system.long_description
  %dt Changing the constitution
  %dd
    = render :partial => 'shared/propose_voting_system_amendment_form', :locals => {:type => 'constitution', :description => 'Change the way the constitution is changed:'}
    The constitution may only be amended by a decision where
    = @constitution_voting_system.long_description(:include_received => true)
  %dt Admitting and rejecting members
  %dd
    = render :partial => 'shared/propose_voting_system_amendment_form', :locals => {:type => 'membership', :description => 'Change the way membership decisions are made:'}
    New members may be appointed and exiting members ejected only by a decision where
    = @membership_voting_system.long_description(:include_received => true)
  %dt Voting period
  %dd
    = render :partial => 'shared/propose_change_voting_period_form'
    = @voting_period
    