config/routes.rb
OneClickOrgs::Application.routes.draw do

  
  match '/settings' => 'one_click#settings', :as => 'settings'
  match '/constitution' => 'one_click#constitution', :as => 'constitution'
  
  match '/timeline' => 'one_click#timeline', :as => 'timeline'
  
  match '/votes/vote_for/:id' => 'votes#vote_for', :conditions => {:method => :post}, :as => 'vote_for'
  match '/votes/vote_against/:id' => 'votes#vote_against', :conditions => {:method => :post}, :as => 'vote_against'
  
  resources :decisions
  resources :proposals
  match '/proposals(/:action)' => 'proposals'
  resources :members do
    member do
      post :change_class
    end
  end
  
  match '/one_click(/:action)' => 'one_click'
  match '/induction(/:action)' => 'induction'
  
  match '/login' => 'member_sessions#new', :as => 'login'
  resource :member_session, :only => [:new, :create, :destroy]
  
  match '/reset_password(/:action)' => 'reset_password'
  
  match '/welcome(/:action)' => 'welcome'
  
  match '/setup(/:action)' => 'setup'
  
  resources :organisations
  
  root :to => 'one_click#dashboard'
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :organisation
  
  after_create :send_email
  
  has_many :votes
  has_one :decision
  
  belongs_to :proposer, :class_name => 'Member', :foreign_key => 'proposer_member_id'
  
  before_create :set_creation_date
  private
  def set_creation_date
    self.creation_date ||= Time.now.utc
  end
  public
  
  before_create :set_close_date
  private
  def set_close_date
    self.close_date ||= Time.now.utc + organisation.constitution.voting_period
  end
  public
  
  validates_presence_of :proposer_member_id
  
  def end_date
    self.close_date
  end
  
  # Returns a Vote by the member specified, or Nil
  def vote_by(member)
    member.votes.where(:proposal_id => self.id).first
  end
  
  def votes_for
    Vote.where(:proposal_id => self.id, :for => true).count
  end
  
  def votes_against
    Vote.where(:proposal_id => self.id, :for => false).count
  end
  
  # returns the number of members who are eligible to vote on this proposal
  def member_count
    # TODO: find out how to do the following in one query
    count = 0
    organisation.members.where(["created_at < ? AND active = ? AND inducted_at IS NOT NULL", creation_date, true]).each do |m|
      count += 1 if m.has_permission(:vote)
    end
    count
  end
  
  def abstained
    member_count - total_votes
  end
  
  def total_votes
    votes_for + votes_against
  end
  
  def reject!
    # TODO do some kind of email notification
  end
  
  def accepted_or_rejected
    accepted? ? "accepted" : "rejected"
  end
  
  def enact!(params={})
  end
  
  def closed?
    ! self.open?
  end
  
  def voting_system
    organisation.constitution.voting_system(:general)
  end
    
  def passed?
    voting_system.passed?(self)
  end
  
  def close!
    raise "proposal #{self} already closed" if closed?   
        
    passed = passed?
    Rails.logger.info("closing proposal #{self}")
        
    self.open = 0
    self.close_date = Time.now
    self.accepted = passed
    save!
    
    if passed
      decision = self.create_decision
      decision.send_email
      
      enact!(self.parameters)
    end
  end

  def parameters
    self[:parameters].blank? ? {} : ActiveSupport::JSON.decode(self[:parameters])
  end
  
  def parameters=(new_parameters)
    self[:parameters] = new_parameters.to_json
  end
  
  def self.find_closeable_early_proposals
    currently_open.all.select { |p| p.voting_system.can_be_closed_early?(p) }
  end

  def self.close_due_proposals
    where(["close_date < ? AND open = ?", Time.now.utc, true]).all.each { |p| p.close! }
  end
  
  def self.close_early_proposals
    find_closeable_early_proposals.each { |p| p.close! }
  end
  
  # Called every 60 seconds in the worker process (set up at end of file)
  def self.close_proposals
    close_due_proposals
    close_early_proposals
  end
  
  scope :currently_open, lambda {where(["open = ? AND close_date > ?", 1, Time.now.utc])}
  
  scope :failed, lambda {where(["close_date < ? AND accepted = ?", Time.now.utc, false]).order('close_date DESC')}
  
  def send_email
    self.organisation.members.active.each do |m|
      # only notify members who can vote
      ProposalMailer.notify_creation(m, self).deliver if m.has_permission(:vote)
    end
  end
  handle_asynchronously :send_email
  
  # only to be backwards compatible with systems running older versions of delayed job
  def self.send_email_for(proposal_id)
    Proposal.find(proposal_id).send_email_without_send_later
  end
  
  def to_event
    {:timestamp => self.creation_date, :object => self, :kind => (closed? && !accepted?) ? :failed_proposal : :proposal }
  end
  
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  respond_to :html
  
  before_filter :require_freeform_proposal_permission, :only => [:create]
  
  before_filter :require_constitutional_proposal_permission, :only => [
    :create_text_amendment, :create_assets_amendment, :create_voting_period_amendment,
    :create_voting_system_amendment]
  
  def index
    # Fetch open proposals
    @proposals = co.proposals.currently_open
    
    # Fetch five most recent decisions
    @decisions = co.decisions.order("id DESC").limit(5)
    
    # Fetch five most recent failed proposals
    @failed_proposals = co.proposals.failed.limit(5)
  end

  def show
    @proposal = co.proposals.find(params[:id])
    respond_with @proposal
  end

  def create
    @proposal = co.proposals.new(params[:proposal])
    @proposal.proposer_member_id = current_user.id #fixme
        
    if @proposal.save
      redirect_to proposal_path(@proposal), :flash => {:notice => "Proposal was successfully created"}
    else
      redirect root_path, :flash => {:error => "Proposal not created"}
    end
  end
  
  def create_text_amendment
    proposal = co.change_text_proposals.new(
      :title => "Change #{params[:name].humanize.downcase} to '#{params[:value]}'",
      :proposer_member_id => current_user.id,
      :parameters => {
        'name' => params[:name],
        'value' => params[:value]
      }
    )
    if proposal.save
      redirect_to({:controller => 'one_click', :action => 'dashboard'}, :notice => "Constitutional amendment proposal succesfully created")
    else
      redirect_to(constitution_path, :flash => {:error => "Error creating proposal: #{proposal.errors.inspect}"})
    end
  end
  
  def create_assets_amendment
    if params[:new_assets_value] == '1'
      title = "Change the constitution to allow holding, transferral and disposal of material assets and intangible assets"
      new_assets_value = true
    else
      title = "Change the constitution to prohibit holding, transferral or disposal of material assets and intangible assets"
      new_assets_value = false
    end
    
    proposal = co.change_boolean_proposals.new(
      :title => title,
      :proposer_member_id => current_user.id,
      :parameters => {
        'name' => 'assets',
        'value' => new_assets_value
      }
    )
    
    if proposal.save
      redirect_to({:controller => 'one_click', :action => 'dashboard'}, :notice => "Constitutional amendment proposal succesfully created")
    else
      redirect_to(constitution_path, :flash => {:error => "Error creating proposal: #{proposal.errors.inspect}"})
    end
  end
  
  def create_voting_period_amendment
    if params[:new_voting_period]
      proposal = co.change_voting_period_proposals.new(
        :title=>"Change voting period to #{VotingPeriods.name_for_value(params[:new_voting_period])}",
        :proposer_member_id => current_user.id,
        :parameters => {'new_voting_period'=>params[:new_voting_period]}
      )
      if proposal.save
        redirect_to({:controller => 'one_click', :action => 'dashboard'}, :notice => "Constitutional amendment proposal succesfully created")
      else
        redirect_to(constitution_path, :flash => {:error => "Error creating proposal: #{proposal.errors.inspect}"})
      end
    end
  end
  
  def create_voting_system_amendment
    if params[:general_voting_system]
      proposed_system = VotingSystems.get(params[:general_voting_system])      
      current_system = co.constitution.voting_system :general
      
      if current_system != proposed_system           
              
        proposal = co.change_voting_system_proposals.new(
          :title => "change general voting system to #{proposed_system.description}",
          :proposer_member_id => current_user.id,
          :parameters => {'type'=>'general', 'proposed_system'=> proposed_system.simple_name}
        )

        if proposal.save
          redirect_to({:controller=>'one_click', :action=>'dashboard'}, :flash => {:notice=> "Change general voting system proposal successfully created"})
        else
          redirect_to constitution_path, :flash => {:error => "Error creating proposal: #{proposal.errors.inspect}"}      
        end

        return
      end
    elsif params[:membership_voting_system]
      proposed_system = VotingSystems.get(params[:membership_voting_system])
      current_system = co.constitution.voting_system :membership
      
      if current_system != proposed_system
        proposal = co.change_voting_system_proposals.new(
          :title => "change membership voting system to #{proposed_system.description}",
          :proposer_member_id => current_user.id,
          :parameters => {'type' => 'membership', 'proposed_system' => proposed_system.simple_name}
        )
        
        if proposal.save
          redirect_to({:controller=>'one_click', :action=>'dashboard'}, :flash => {:notice=> "Change membership voting system proposal successfully created"})
        else
          redirect_to constitution_path, :flash => {:error => "Error creating proposal: #{proposal.errors.inspect}"}
        end
        
        return
      end
    elsif params[:constitution_voting_system]
      proposed_system = VotingSystems.get(params[:constitution_voting_system])
      current_system = co.constitution.voting_system :constitution
      
      if current_system != proposed_system
        proposal = co.change_voting_system_proposals.new(
          :title => "change constitution voting system to #{proposed_system.description}",
          :proposer_member_id => current_user.id,
          :parameters => {'type' => 'constitution', 'proposed_system' => proposed_system.simple_name}
        )
        
        if proposal.save
          redirect_to({:controller=>'one_click', :action=>'dashboard'}, :flash => {:notice=> "Change constitution voting system proposal successfully created"})
        else
          redirect_to constitution_path, :flash => {:error => "Error creating proposal: #{proposal.errors.inspect}"}
        end
        
        return
      end
      
    
    end
    
    redirect_to constitution_path, :flash => {:error => "No changes."}                
  end

private

  def require_freeform_proposal_permission
    if !current_user.has_permission(:freeform_proposal)
      flash[:error] = "You do not have sufficient permissions to create such a proposal!"
      redirect_back_or_default
    end
  end
  
  def require_constitutional_proposal_permission
    if !current_user.has_permission(:constitution_proposal)
      flash[:error] = "You do not have sufficient permissions to create such a proposal!"
      redirect_back_or_default
    end
  end

end # Proposals

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_description.html.haml
- paras = []
- paras = proposal.description.split("\n") if proposal.description
%div.description
  - for para in paras
    %p= para

app/views/proposals/_vote.html.haml
- if current_user.has_permission(:vote)
  - if proposal.vote_by(current_user)
    You voted to
    %strong
      = proposal.vote_by(current_user).for_or_against.upcase
  - else
    = form_tag(vote_for_path(:id => proposal.id, :return_to => request.url)) do
      = submit_tag "Support"
    = form_tag(vote_against_path(:id => proposal.id, :return_to => request.url)) do
      = submit_tag "Oppose"

app/views/proposals/_vote_count.html.haml
- votes_for = proposal.votes.select{|v| v.for?}.size
- votes_against = proposal.votes.select{|v| ! v.for?}.size

= votes_for 
Support
\/ 
= votes_against
Oppose

app/views/proposals/index.html.haml
%h3 Proposals

%p= "..."

%h4 Open Proposals
%table.proposals
  %tr
    %th Title
    %th End in
    %th Vote
  - for proposal in @proposals
    %tr{:class => cycle('odd', 'even')}
      %td
        = proposal.title
        (
        = link_to(proposal.proposer.name, member_path(proposal.proposer))
        )
        = render 'proposals/description', :proposal => proposal
        %p= link_to("More details", proposal_path(proposal))
      %td.timestamp
        = distance_of_time_in_words_to_now(proposal.end_date)
      %td.vote
        = render 'proposals/vote', :proposal => proposal
  
%h4 Recent Decisions
%table.decisions
  %tr
    %th Title
    %th Decision made
    %th For/against
  - reset_cycle
  - for decision in @decisions
    %tr{:class => cycle('odd', 'even')}
      %td
        = decision.proposal.title
        (
        = link_to(decision.proposal.proposer.name, member_path(decision.proposal.proposer))
        )
        = render 'proposals/description', :proposal => decision.proposal
        %p= link_to("More details", proposal_path(decision.proposal))
      %td.timestamp= decision.proposal.close_date.to_s(:long)
      %td.vote= render 'proposals/vote_count', :proposal => decision.proposal

%h4 Recent Failed Proposals
%table.failed_proposals
  %tr
    %th Title
    %th Proposal failed
    %th For/against
  - reset_cycle
  - for failed_proposal in @failed_proposals
    %tr{:class => cycle('odd', 'even')}
      %td
        = failed_proposal.title
        (
        = link_to(failed_proposal.proposer.name, member_path(failed_proposal.proposer))
        )
        = render 'proposals/description', :proposal => failed_proposal
        %p= link_to("More details", proposal_path(failed_proposal))
      %td.timestamp= failed_proposal.close_date.to_s(:long)
      %td.vote= render 'proposals/vote_count', :proposal => failed_proposal

app/views/proposals/show.html.haml
- if @proposal.open?
  %h3
    Proposal:
    = @proposal.title
- elsif @proposal.accepted?
  %h3
    Decision:
    = @proposal.title
- else
  %h3
    Failed proposal:
    = @proposal.title

= render 'description', :proposal => @proposal

%p
  Proposed by
  = link_to(@proposal.proposer.name, @proposal.proposer)
  = @proposal.creation_date.to_s(:at_on)

- if @proposal.open?
  %p
    Voting ends
    = @proposal.end_date.to_s(:at_on)
  %p
    Time remaining:
    = distance_of_time_in_words_to_now(@proposal.end_date)

- if @proposal.open?
  - if current_user.has_permission(:vote)
    %p
      = render 'vote', :proposal => @proposal
  - else
    %p
      You cannot vote on this proposal.
- else
  %p
    This proposal
    -if @proposal.accepted?
      %strong SUCCEEDED
    -else
      %strong FAILED

%p
  Vote count:
  = render 'vote_count', :proposal => @proposal
    