config/routes.rb
OneClickOrgs::Application.routes.draw do

  
  match '/settings' => 'one_click#settings', :as => 'settings'
  match '/constitution' => 'one_click#constitution', :as => 'constitution'
  
  match '/timeline' => 'one_click#timeline', :as => 'timeline'
  
  match '/votes/vote_for/:id' => 'votes#vote_for', :conditions => {:method => :post}, :as => 'vote_for'
  match '/votes/vote_against/:id' => 'votes#vote_against', :conditions => {:method => :post}, :as => 'vote_against'
  
  resources :decisions
  resources :proposals
  match '/proposals(/:action)' => 'proposals'
  resources :members do
    member do
      post :change_class
    end
  end
  
  match '/one_click(/:action)' => 'one_click'
  match '/induction(/:action)' => 'induction'
  
  match '/login' => 'member_sessions#new', :as => 'login'
  resource :member_session, :only => [:new, :create, :destroy]
  
  match '/reset_password(/:action)' => 'reset_password'
  
  match '/welcome(/:action)' => 'welcome'
  
  match '/setup(/:action)' => 'setup'
  
  resources :organisations
  
  root :to => 'one_click#dashboard'
end

app/models/member.rb
require 'digest/sha1'
require 'lib/vote_error'

class Member < ActiveRecord::Base
  belongs_to :organisation
  
  has_many :votes
  has_many :proposals, :foreign_key => 'proposer_member_id'
  belongs_to :member_class

  scope :active, where(["active = ? AND inducted_at IS NOT NULL", 1])
  scope :pending, where("inducted_at IS NULL")
  
  def proposals_count
    proposals.count
  end
  
  def succeeded_proposals_count
    proposals.where(:open => false, :accepted => true).count
  end
  
  def failed_proposals_count
    proposals.where(:open => false, :accepted => false).count
  end
  
  def votes_count
    votes.count
  end

  # AUTHENTICATION

  attr_accessor :password, :password_confirmation

  # Encrypts some data with the salt
  def self.encrypt(password, salt)
    Digest::SHA1.hexdigest("--#{salt}--#{password}--")
  end

  def self.authenticate(login, password)
    member = where(:email => login).first
    member && member.authenticated?(password) ? member : nil
  end

  def authenticated?(password)
    crypted_password == encrypt(password)
  end

  def encrypt(password)
    self.class.encrypt(password, salt)
  end

  def password_required?
    crypted_password.blank? || !password.blank?
  end

  def encrypt_password
    return if password.blank?
    self.salt = Digest::SHA1.hexdigest("--#{Time.now.to_s}--:email--") if new_record?
    self.crypted_password = encrypt(password)
  end

  before_save :encrypt_password

  # END AUTHENTICATION

  def cast_vote(action, proposal_id)
    raise ArgumentError, "need action and proposal_id" unless action and proposal_id

    existing_vote = Vote.where(:member_id => self.id, :proposal_id => proposal_id).first
    raise VoteError, "Vote already exists for this proposal" if existing_vote

    # FIXME why not just pass the proposal in?
    proposal = organisation.proposals.find(proposal_id)
    raise VoteError, "proposal with id #{proposal_id} not found" unless proposal
    if !self.inducted? || proposal.creation_date < self.inducted_at
      raise VoteError, "Can not vote on proposals created before member inducted"
    end

    case action
    when :for
      Vote.create(:member => self, :proposal_id => proposal_id, :for => true)
    when :against
      Vote.create(:member => self, :proposal_id => proposal_id, :for => false)
    end
  end

  def new_password!(n=6)
    raise ArgumentError, "password must have at least 6 characters" if n < 6
    chars = ["a".."z", "A".."Z", "0".."9"].map(&:to_a).flatten
    self.password = self.password_confirmation = (1..n).map { chars[rand(chars.size-1)] }.join
  end

  def self.create_member(params, send_welcome=false)
    member = Member.new(params)
    member.new_password!
    member.save!
    member.send_welcome if send_welcome
    member
  end

  def send_welcome
    # delayed_job will not have access to the instance variable @password
    # when it reloads this Member object, so we cache it in the method
    # parameters here.
    self.dispatch_welcome(self.password)
  end
  
  def dispatch_welcome(cached_password)
    MembersMailer.welcome_new_member(self, cached_password).deliver
  end
  handle_asynchronously :dispatch_welcome
  
  # only to be backwards compatible with systems running older versions of delayed job
  def self.send_new_member_email(member_id, password)
    Member.find(member_id).send_welcome_without_send_later
  end
    
  def eject!
    self.active = false
    save
  end

  def inducted?
    !inducted_at.nil?
  end

  def to_event
    if self.inducted?
      {:timestamp => self.inducted_at, :object => self, :kind => :new_member}
    end
  end
  
  def has_permission(type)
    member_class.has_permission(type)
  end
  
  def name
    full_name = [first_name, last_name].compact.join(' ')
    full_name.blank? ? nil : full_name
  end
end

app/controllers/members_controller.rb
require 'lib/not_found'

class MembersController < ApplicationController

  respond_to :html
  
  before_filter :require_membership_proposal_permission, :only => [:new, :create, :update, :destroy, :change_class]

  def index
    @members = co.members.active
    @pending_members = co.members.pending
    @new_member = co.members.new
    respond_with @members
  end

  def show
    @member = co.members.find(params[:id])
    raise NotFound unless @member
    
    @timeline = [
      @member,
      @member.proposals.all,
      @member.votes.all
    ].flatten.map(&:to_event).compact.sort{|a, b| b[:timestamp] <=> a[:timestamp]}
    
    respond_with @member
  end

  def new
    # only_provides :html
    @member = co.members.new
    respond_with @member
  end

  def edit
    # only_provides :html
    @member = co.members.find(params[:id])
    unless current_user.id == params[:id].to_i
      flash[:error] = "You are not authorized to do this."
      redirect_back_or_default
      return
    end
    respond_with @member
  end

  def create
    member = params[:member]
    title = "Add #{member['name']} as a member of #{current_organisation.organisation_name}" # TODO: should default in model
    proposal = co.add_member_proposals.new(
      :title => title,
      :proposer_member_id => current_user.id,
      :parameters => member
    )
    
    if proposal.save
      redirect_to members_path, :notice => "Add Member Proposal successfully created"
    else
      redirect_to members_path, :flash => {:error => "Error creating proposal: #{@member.errors.inspect}"}      
    end
  end


  def update
    id, member = params[:id], params[:member]
    @member = co.members.find(id)
    if @member.update_attributes(member)
       redirect_to member_path(@member), :notice => "Member updated"
    else
      flash[:error] = @member.errors.inspect
      render(:action => :edit)
    end
  end

  def destroy
    @member = co.members.find(params[:id])
    
    title = "Eject #{@member.name} from #{current_organisation.organisation_name}"
    proposal = co.eject_member_proposals.new(
      :title => title,
      :proposer_member_id => current_user.id,
      :parameters => {'id' => @member.id}
    )
    
    if proposal.save
      redirect_to({:controller => 'one_click', :action => 'dashboard'}, :notice => "Ejection proposal successfully created")
    else
      redirect member_path(@member), :flash => {:error => "Error creating proposal: #{proposal.errors.inspect}"}
    end
  end
  
  def change_class
    @member = co.members.find(params[:id])
    @new_member_class = co.member_classes.find(params[:member][:member_class_id])
    
    title = "Change member class of #{@member.name} from #{@member.member_class.name} to #{@new_member_class.name}"
    proposal = co.change_member_class_proposals.new(
      :title => title,
      :proposer_member_id => current_user.id,
      :description => params[:description],
      :parameters => ChangeMemberClassProposal.serialize_parameters(
        'id' => @member.id, 
        'member_class_id' => @new_member_class.id)
    )
    
    if proposal.save
      flash[:notice] = "Membership class proposal successfully created"
      redirect_back_or_default(member_path(@member))
    else
      flash[:error] = "Error creating proposal: #{proposal.errors.inspect}"
      redirect_back_or_default(member_path(@member))
    end
  end

private

  def require_membership_proposal_permission
    if !current_user.has_permission(:membership_proposal)
      flash[:error] = "You do not have sufficient permissions to create such a proposal!"
      redirect_back_or_default
    end
  end

end # Members

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit.html.haml
%h3
  Edit Profile

%p
  = form_for(@member, :url => member_path(@member), :html => {'class' => 'member'}) do |f|
    %p
      = f.label(:first_name)
      = f.text_field :first_name
    %p
      = f.label(:last_name)
      = f.text_field :last_name
    %p
      = f.label(:email, "Email Address")
      = f.text_field :email
    %p
      = f.label(:password)
      = f.password_field :password
    %p
      = f.label(:password_confirmation, "repeat password")
      = f.password_field :password_confirmation
    %p    
      = submit_tag "Save Profile", :id => 'submit'

app/views/members/index.html.haml
%h3
  Existing Members
%table.members
  %thead
    %tr
      %th Name
      %th Proposals made (succeeded/failed)
      %th Votes cast
  - for member in @members
    %tr
      %td= link_to "#{member.name}", member_path(member)
      %td
        = member.proposals_count
        (
        = member.succeeded_proposals_count
        \/
        = member.failed_proposals_count
        )
      %td= member.votes_count
- unless @pending_members.empty?
  %h3
    Pending Members
  %p
    These members still need to agree to the constitution
  %ul
    - for member in @pending_members
      %li
        = link_to "#{member.name}", member_path(member)

app/views/members/show.html.haml
%h3
  = @member.name

%p
  = mail_to(@member.email)

%p
  Proposals made:
  = @member.proposals_count
  Succeeded:
  = @member.succeeded_proposals_count
  Failed:
  = @member.failed_proposals_count

%p
  Proposals voted on:
  = @member.votes_count

- if current_user.has_permission(:membership_proposal)

  - if MemberClass.count > 1
    %h4
      Change Member Class

    %p
      Create a proposal to change the member class of this member. Current class: 
      = @member.member_class.name

    = form_tag(change_class_member_path(@member)) do
      %p
        = label_tag(:description)
        = text_area_tag :description
      %p
        = label_tag(:class)
        = collection_select(:member, :member_class_id, 
          MemberClass.all.reject {|mc| mc==@member.member_class }, :id, :name)
      %p
        = submit_tag "Create Proposal", :id => 'submit'

  %h4
    Propose the ejection of this member

  = form_tag(member_path(@member), :method => :delete) do
    %p
      = label_tag(:description)
      = text_area_tag :description
    %p
      = submit_tag "Create proposal to eject this member", :id => 'submit'


%h4 Timeline for this member
%table.timeline
  - for event in @timeline
    %tr
      = render :partial => "one_click/#{event[:kind]}", :locals => {:event => event}